"""
Lift the corporate seal out of the supplied paper mockup.

The source is a photograph: the seal sits on textured stock, rotated 2.1 degrees,
on a grey studio background. This deskews it, keys the paper out into an alpha
channel, and re-inks the result in the exact brand blue so the mark is crisp at
any size and can be tinted for dark sections.
"""

from PIL import Image
import hashlib
import io as _io
import math
import os
import shutil

SRC = "wikitech group logo.jpeg"
OUT = "public/brand"
TILT = -2.111          # measured from the rule beneath the gear
CENTER = (800.0, 439.0)
RADIUS = 370.0

BRAND = (18, 51, 138)   # --color-brand-700
WHITE = (255, 255, 255)

PAPER_L = 228.0         # measured paper luminance
INK_L = 42.0            # measured ink luminance
LO, HI = 0.22, 0.86     # curve that discards paper grain, keeps stroke edges

os.makedirs(OUT, exist_ok=True)

src = Image.open(SRC).convert("RGB")

# 1 — deskew about the seal centre, at full resolution so nothing is lost.
level = src.rotate(TILT, resample=Image.BICUBIC, center=CENTER, fillcolor=(234, 232, 229))

# 2 — crop a square with a little breathing room around the outer ring.
pad = int(RADIUS * 1.045)
box = (
    int(CENTER[0] - pad), int(CENTER[1] - pad),
    int(CENTER[0] + pad), int(CENTER[1] + pad),
)
seal = level.crop(box)
size = seal.size[0]

# 3 — build alpha from ink darkness, masked to the seal's circle so the paper
#     edge and studio background never bleed in.
px = seal.load()
alpha = Image.new("L", seal.size, 0)
ap = alpha.load()
cc = size / 2.0
rlimit = cc - 1.0
span = PAPER_L - INK_L
curve = HI - LO

for y in range(size):
    dy = y - cc
    for x in range(size):
        dx = x - cc
        if dx * dx + dy * dy > rlimit * rlimit:
            continue
        r, g, b = px[x, y]
        lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
        inkness = (PAPER_L - lum) / span
        a = (inkness - LO) / curve
        if a <= 0:
            continue
        ap[x, y] = 255 if a >= 1 else int(a * 255 + 0.5)


def inked(rgb, px_size):
    """Solid-colour seal with the extracted alpha, downsampled for antialiasing."""
    img = Image.new("RGBA", seal.size, rgb + (0,))
    img.putalpha(alpha)
    return img.resize((px_size, px_size), Image.LANCZOS)


# Right-sized WebP for the site, content-hashed so a re-cut mark can never be
# served from a stale cache. The OG generator needs a PNG (satori cannot
# decode WebP) and reads it from disk, so that one keeps a stable name.
if os.path.isdir(OUT):
    shutil.rmtree(OUT)
os.makedirs(OUT, exist_ok=True)

brand_manifest = {}
for name, rgb, px in [("seal", BRAND, 256), ("seal-light", WHITE, 512), ("seal-large", BRAND, 512)]:
    buf = _io.BytesIO()
    inked(rgb, px).save(buf, "WEBP", quality=88, method=6)
    data = buf.getvalue()
    digest = hashlib.sha256(data).hexdigest()[:8]
    with open(f"{OUT}/{name}.{digest}.webp", "wb") as f:
        f.write(data)
    brand_manifest[name] = (f"/brand/{name}.{digest}.webp", px)

inked(WHITE, 256).save(f"{OUT}/seal-light-og.png", optimize=True)

with open("src/data/brand.ts", "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by scripts/extract-logo.py - do not edit by hand.\n")
    f.write("// The corporate seal, lifted from the supplied artwork. Filenames are\n")
    f.write("// content-hashed, so a re-cut mark is never served from a stale cache.\n\n")
    f.write("export const seal = {\n")
    for name, (src, px) in brand_manifest.items():
        key = name.replace("seal-", "").replace("seal", "brand")
        f.write(f'  {key}: {{ src: "{src}", size: {px} }},\n')
    f.write("} as const;\n")

# Favicons: the seal on a white disc, so it reads on light and dark browser chrome.
from PIL import ImageDraw

def favicon(px):
    img = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    ImageDraw.Draw(img).ellipse((0, 0, px - 1, px - 1), fill=(255, 255, 255, 255))
    inner = int(px * 0.96)
    s = inked(BRAND, inner)
    img.paste(s, ((px - inner) // 2, (px - inner) // 2), s)
    return img.quantize(colors=64, method=Image.FASTOCTREE)

favicon(192).save("src/app/icon.png", optimize=True)
favicon(180).save("src/app/apple-icon.png", optimize=True)

print("crop size:", size, "-> exported 1024px masters")
op = alpha.resize((1024, 1024), Image.LANCZOS)
hist = op.histogram()
print("alpha: fully transparent px =", hist[0], "fully opaque px =", hist[255])
