// AUTO-GENERATED by scripts/extract-logo.py - do not edit by hand.
// The corporate seal, lifted from the supplied artwork. Filenames are
// content-hashed, so a re-cut mark is never served from a stale cache.

export const seal = {
  brand: { src: "/brand/seal.85574da9.webp", size: 256 },
  light: { src: "/brand/seal-light.e558737c.webp", size: 512 },
  large: { src: "/brand/seal-large.be24ef8e.webp", size: 512 },
} as const;
