// AUTO-GENERATED by scripts/build-images.py - do not edit by hand.
// 35 photographs from Pexels (free for commercial use, no attribution
// required). Sources are listed in CREDITS.md.

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const images = {
  "bg/about": {
    src: "/img/bg/about.fc6841af.webp",
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoOAAcAA4BaJZwAAmhxcwIAAP7aoRDwXfMrkk2vK6i0iAvlNRJVX81Tfib2KJzUaO4OAA==",
  },
  "bg/ai": {
    src: "/img/bg/ai.24728f09.webp",
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoOAAcAA4BaJaQAAltbJJgAAP71oibmGDbJ4LL8XEnl8ngdNg9f8WS2FlTNDC4xGh6aZJvCAAA=",
  },
  "bg/contact": {
    src: "/img/bg/contact.393bf322.webp",
    width: 1600,
    height: 760,
    blurDataURL:
      "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoOAAYAA4BaJaQAA3AA/u9c96vufFO8AAA=",
  },
  "bg/final-cta": {
    src: "/img/bg/final-cta.3b30753e.webp",
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoOAAcAA4BaJZACdACd/6g0AAD+iWRS+/hC8b8wFAG9Pbq4ajUmR0FX82K4nt8OpWuW3abNahL9wblIr1WT9SRjxZwAAA==",
  },
  "bg/hero": {
    src: "/img/bg/hero.16b9ffb0.webp",
    width: 1920,
    height: 1080,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoOAAcAA4BaJZwAAsZRBR2AAAD9TtaCPZMo1Qbp3iMQLE7Apv6rCKo5kQdTF3HBT0AAAA==",
  },
  "bg/infrastructure": {
    src: "/img/bg/infrastructure.6bef0b88.webp",
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoOAAcAA4BaJZQC7AEQXNuSmIhAAP70iNt7bh/+nWH0Cwq9av5hrlxqHpnAAA==",
  },
  "bg/why-us": {
    src: "/img/bg/why-us.d46b58e5.webp",
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoOAAcAA4BaJZQAAxPrO/pjwAD+uoPhKioQ7Vd0QCBx1gPFXE1waQcWHrznU9tITjswmOo+fLE2sIbwAbPBwAAA",
  },
  "case/invoice-ocr": {
    src: "/img/case/invoice-ocr.1c884349.webp",
    width: 900,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoOAAcAA4BaJZwAAhERXQAA/umPO7oSPt/0IN5ab5Ak+m7tz7YDq/n/31t4AnP/wACHrZNjX39+CNCq6MWdLMAA",
  },
  "case/multi-entity-erp": {
    src: "/img/case/multi-entity-erp.315d0cc3.webp",
    width: 900,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoOAAcAA4BaJZQAAjwz6VrcgAD+9b7fE0XO3vo4dS7epJAMWS3GKNzxn5lCq0w8l5YJZXrios9iXZUnblPR146BAAA=",
  },
  "case/multi-jurisdiction-tax": {
    src: "/img/case/multi-jurisdiction-tax.75f552a1.webp",
    width: 900,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoOAAcAA4BaJQBdgB2SBZ4AAPzmBygDTp/RqKP4Y875k9D5gD2HpDbe2bf/rLFH5tAAAA==",
  },
  "case/offshore-pod": {
    src: "/img/case/offshore-pod.5c4af09b.webp",
    width: 900,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoOAAcAA4BaJZQCsAEQQne3+AAA/thSskMh7f6GaE0MhABVrecDsdfaVtVGNcvteTI4Re9yBtEHnZjuzDo39HErQcAAAA==",
  },
  "case/ot-it-visibility": {
    src: "/img/case/ot-it-visibility.b9cfa068.webp",
    width: 900,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoOAAcAA4BaJQBOgBJvAdYAAP5y+DQjsQ67oNY4CYdfH3vWbJlOBwomJX+WsLZvd50n9DT1sj4lYnEJMBMAZ3cBF8KVwzt25k24CoaAAAA=",
  },
  "case/storefront-to-ledger": {
    src: "/img/case/storefront-to-ledger.e110b711.webp",
    width: 900,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoOAAcAA4BaJYwCdAEVN2yK0xdQAAD9U48lvEmzt+QH3xFD96UqrmXPKJLVRFj0pqvyR3cbg1fJQcz6ryMyHuyQXe6oJrpuzAA=",
  },
  "cycle/ap-ar": {
    src: "/img/cycle/ap-ar.ad4d89e0.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoOAAgAA4BaJaQAAxcX0IJqAAD+x0rBXGASz+yiVmXkO0gRzmhA7pSAAAA=",
  },
  "cycle/bookkeeping": {
    src: "/img/cycle/bookkeeping.f787f76c.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoOAAgAA4BaJYgCdAYq/YkQ/2gAAP7y6pONN8XFQo47G+XWoxsC9zDNLr3haxJJpz4b3E3UUyh4iEo0D8YZVFLtP4/XB/AjzkXd5JTRkt3jq9ziv07G6AAA",
  },
  "cycle/close": {
    src: "/img/cycle/close.bf2295b0.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoOAAgAA4BaJbACdAYv1UC9re3QAP14Crbft+ralcYLSdRZYfZSFgFBl3TL7tfq/jzMyYjHlNGeq6gEFFfpuXcTfxBcFqXFxE7UwCF6rr1ZpQ9lb+gAAA==",
  },
  "cycle/reporting": {
    src: "/img/cycle/reporting.36ddcceb.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoOAAgAA4BaJQBdgCBvDOsJAUAA/udC1Vq7USp4KVQAl3N4otFNOtyU8Em1h3MCLBirbCIXiJLd4XjPAAA=",
  },
  "cycle/transactions": {
    src: "/img/cycle/transactions.b18b0470.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoOAAgAA4BaJZACdAEe6QhccuggAP7rL4+TDTOx94iF7UK9kaZv9euOyi4mHX5yOlzlOjR1FLgtOJ6EOYqbqpFuItCpdaQH/Z60AAAA",
  },
  "funnel/capture": {
    src: "/img/funnel/capture.118126af.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoOAAgAA4BaJZgAAvtQ3lYAAP3eNM3VCOTAMySZyQUNdtimdzlitJW86T3zD0Byf8/70tgAAAA=",
  },
  "funnel/crm": {
    src: "/img/funnel/crm.f895c1b4.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoOAAgAA4BaJZwAApGC5d3wAAD+765wTiGIvitTNAO8p7Hq0wJyzP4k/2rzdIRItIlTiB+povsqZ1rxQAA=",
  },
  "funnel/demand": {
    src: "/img/funnel/demand.1077714e.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoOAAgAA4BaJbACdADLwV9MoAD+m9G1cvNm7svnB8QUn2Lo+rbxdjTMpQlBmZugyieThMgMGwX/a5UXm6S1X7NHLBTxG1ZRHB2EgnLt8plAyEsMKQnKsuAA",
  },
  "funnel/qualify": {
    src: "/img/funnel/qualify.c866e339.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoOAAgAA4BaJQBOgMXhzwhdheYqfAD+W9j5Uy6s+GPK1/FCTQl7CX8mZfo4Trh8Lt7KLpvwO5CI2gtt00t5u7qFNzKfOEGae5R5UAgBRqOmgYsPgtkHWXeO5gAAAA==",
  },
  "phase/blueprint": {
    src: "/img/phase/blueprint.391614b9.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoOAAgAA4BaJaQAAu0SRyYAAP7nWBMRucO5LnHTsFp2PMbBBZfVr/44MJ+QzAAA",
  },
  "phase/hypercare": {
    src: "/img/phase/hypercare.0db4881d.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoOAAgAA4BaJZgCdAC6Qxy1wAD+nAELVOcwD3240JQd1t+f+HQdclbYVF82zu6VEyNjyal4Ls49rkyaooeSLNIncaLCNII7SWhYgXJlVpAAAA==",
  },
  "phase/migrate": {
    src: "/img/phase/migrate.41764bda.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoOAAgAA4BaJQBdgCPlhpVgAP2UkXlyeIPDkraPHFpJ3Y0uQxOVaimdo+osmWuywXArJFKoAAA=",
  },
  "phase/re-engineer": {
    src: "/img/phase/re-engineer.1257de52.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoOAAgAA4BaJYwCdAYtzbZt83NYAPwOtaggBim6q9AoDnmj87HNBix6GYtQybPKkr1zLbvg+P14OTGJFEt0FrLWpQllabztsZLDgAAA",
  },
  "phase/train": {
    src: "/img/phase/train.cbbb8a51.webp",
    width: 640,
    height: 400,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoOAAgAA4BaJZQAD4eQ32fdgAD9AzawPb5SNuvCYTQnVzUxav82Hew8sa0RJIgMJ3EHxdj7Iv31rhrKB8sFbs/XXBrpgcAA",
  },
  "service/accounting": {
    src: "/img/service/accounting.674fafc6.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoOAAgAA4BaJQBOgCPzVSXfxZAAAP5lUcbhLRQgFNQjQOORRK+WSN9YOesAAA==",
  },
  "service/ai": {
    src: "/img/service/ai.313ae322.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAACQAQCdASoOAAgAA4BaJaQAAxf7+RAA/vLam/wdmAAAAA==",
  },
  "service/erp": {
    src: "/img/service/erp.0161873b.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABQAgCdASoOAAgAA4BaJYwC7AYtB21wN1AwwYAA/knvJfowgdRivzESq/kxhiv/3bHYH/GQVOkNV8wmoS6IkGpgG9bs7B6W9JByHIAA",
  },
  "service/forecasting": {
    src: "/img/service/forecasting.f5bc6890.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoOAAgAA4BaJaQAAqzIqnVCAAD+9VlJMplR9vF4cDfMT6iDFGI9NJ44/3mxjumn3dlMBnYXbXkgAAAA",
  },
  "service/infrastructure": {
    src: "/img/service/infrastructure.83b76783.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoOAAgAA4BaJYgCdADdLUeSigAA/vkX9VMz2wx1RKTZz4nxG9cr9bJR6JfaNl2CpdoO8g6jlSirQfkPp8strRqMAAA=",
  },
  "service/integrations": {
    src: "/img/service/integrations.efd41c41.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoOAAgAA4BaJQBOgCHpZqbc6AD2iXlQHVOvWASjojPVvi+x/2nKaZEsXSPPN4b+PtHIt3cu4/tB8XLmGJbAAA==",
  },
  "service/marketing": {
    src: "/img/service/marketing.34ebe9da.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoOAAgAA4BaJYwCdAEQ5WlxTFZAAP7CrKFM92Ad8OkHPPX+ob2muty7w9IE/QTBiyrwmoz4fakF3lluEf6PYZP/NztWcehAWB4RT+HlsNGVPQAA",
  },
  "service/tax": {
    src: "/img/service/tax.df788c28.webp",
    width: 800,
    height: 500,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAgCdASoOAAgAA4BaJQBOj+Ef/AvI4W+tJveioAD+wRk2scN8NowgGvWgkn/Ei1vFmOnXp9rkw2lwnGRrfuQlU1IYMypBJ8M0au97qt1B2SGuPr6polgA",
  },
} as const satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof images;
